services:
  postgres:
    image: postgres:17
    container_name: tuka_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: tuka_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
